name: R-workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Restore renv cache
        uses: actions/cache@v3
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: renv-${{ hashFiles('renv.lock') }}

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            pandoc pandoc-citeproc texlive-latex-base texlive-fonts-recommended \
            libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: renv restore
        run: |
          R -q -e "install.packages('renv'); renv::restore()"

      - name: Execute analysis scripts
        run: |
          Rscript analysis/01_data-cleaning.R
          Rscript analysis/03_RMST_analysis.R

      - name: Render manuscript (PDF + HTML)
        run: |
          R -q -e "rmarkdown::render('manuscript/PARIST_manuscript.Rmd', output_dir = 'docs', output_format = c('pdf_document','html_document'))"

      - name: Upload rendered outputs
        uses: actions/upload-artifact@v4
        with:
          name: manuscript
          path: docs/

      #- name: Deploy to Pages
      #  if: github.ref == 'refs/heads/main'
      #  uses: peaceiris/actions-gh-pages@v4
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: docs
